Order view
mwcschool/ecommerce_api pull request #10
Opened 2017-05-08 15:21 UTC by Vincenzo10

2017-05-08 19:06 UTC, GendoIkari commented on tests/test_order.py
> +        User._meta.database = SqliteDatabase(':memory:')
In ogni caso mi piace poco questa ripetizione.
```python
db = SqliteDatabase(':memory:')
User._meta.database = db
....
```

2017-05-08 19:06 UTC, GendoIkari commented on tests/test_order.py
> +        assert Order.get(order_id=order['order_id']).json() == order
Dividiamo queste righe complicate usando un po' di variabili di supporto.

2017-05-08 19:06 UTC, GendoIkari commented on tests/test_order.py
> +        source_order = {
Source order? Diamo un nome piu' semplice.

2017-05-08 19:06 UTC, GendoIkari commented on tests/test_order.py
> +        assert resp.status_code == BAD_REQUEST
Controlliamo che il database non sia stato toccato. Facciamo una len che sia zero.
```python
assert len(Order.select()) == 0
```

2017-05-08 19:06 UTC, GendoIkari commented on views/order.py
> +        user = User.get(User.user_id == args['user'])
Se lo user non c'e', qui fa un 500. Questo significa che non c'e' un test per questo. Se c'e' non va e va fixato, se non c'e' va scritto.

2017-05-08 19:06 UTC, GendoIkari commented on views/order.py
> +            instance = Order.get(order_id=order_id)
Instance non vuol dire nulla. old_order? order?

2017-05-09 13:00 UTC, gvaldambrini commented
Come detto a voce, in questo momento mancando l'integrazione di un OrderItem il lavoro è zoppo. A questo punto creiamo un nuovo branch dove aggiungere l'integrazione, e lasciamo questo per la roba base dell'Order.

2017-05-12 09:04 UTC, gvaldambrini requested changes

2017-05-12 09:04 UTC, gvaldambrini commented on tests/test_order.py
> +        usr1 = User.create(
evitiamo abbreviazioni inutili, a maggior ragione per risparmiare un carattere. Quindi usiamo `user`, `order`, ecc...

2017-05-12 09:04 UTC, gvaldambrini commented on tests/test_order.py
> +        User.delete().execute()
Ma che bisogno c'è di eliminare e creare un utente ogni volta? Non si potrebbe creare un utente nella setup_class, salvarlo nella classe e poi riutilizzarlo nei test dopo?

2017-05-12 09:04 UTC, gvaldambrini commented on tests/test_order.py
> +        assert len(User.select()) == 0
questo assert direi che ce lo possiamo risparmiare, visto che il test è sugli ordini no?

2017-05-12 09:04 UTC, gvaldambrini commented on tests/test_order.py
> +        assert resp.status_code == BAD_REQUEST
qua andrebbe verificato che l'ordine non sia creato per davvero, quindi la select andrebbe fatta come negli altri casi

2017-05-12 09:04 UTC, gvaldambrini commented on tests/test_order.py
> +        )
dopo la fallita modifica andrebbe verificato che l'ordine creato a mano sia l'unico e che non sia stato modificato per errore

2017-05-12 09:04 UTC, gvaldambrini commented on views/order.py
> +            total_price=float(args['total_price']),
siamo sicuri che ci sia bisogno di questo cast? dovrebbe pensarci reqparse a fare la conversione a float, sbaglio?

2017-05-12 15:26 UTC, Vincenzo10 commented
Annulliamo questa pull request perché fa riferimento al branch non aggiornato.

2017-05-12 15:26 UTC, closed without merging