21 aggiungere i preferiti
mwcschool/ecommerce_api pull request #42
Opened 2017-05-21 14:04 UTC by Ryukaj95

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +        return favorite.json(), CREATED
```
return favorite
```

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +    def add_favorite(this, item):
Refuso javascriptoso? E' self.

2017-05-22 12:47 UTC, GendoIkari commented on views/favorites.py
> +        if not User.exists_uuid(args['id_user']) or not Item.exists_uuid(args['id_item']):
```python
try:
    User.get(User.user_id == args['id_user'])
except User.DoesNotExist:
    return None, NOT_FOUND
```

2017-05-22 12:47 UTC, GendoIkari commented on views/favorites.py
> +            user = User.select().get()
User.get() == User.select().get()

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +            return False
Questa non serve.

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +        return None, NO_CONTENT
A questo livello non voglio fare i check, assumo che item sia corretto, e non voglio sapere niente di http.

Questo poi o e' un nome sbagliato o e' un bug.

```
def remove_favorite(self, item):
   Favorites.select().where(Favorites.item == item and Favorites.user == self).delete()
```

2017-05-22 12:47 UTC, GendoIkari commented on views/favorites.py
> +                )
Una di queste due query e' ridondante.

```python
try:
    Favorites.select().where(Favorites.user == user and Favorites.item == item).get()
except ...
```

2017-05-22 12:47 UTC, GendoIkari commented on views/favorites.py
> +            return None, NOT_FOUND
```
try:
    item = Item.get(Item.item_id == item_id)
except ....
```

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +            'item': str(self.item)
Forse volevi dire: `'user': str(self.user.user_id)`. E comunque questa funziona non e' mai usata, perche' la get di favorites prende una lista di item.

2017-05-22 12:47 UTC, GendoIkari commented on models.py
> +        return [favorite.item.json() for favorite in self.favorites]
`def favorite_items(self):`.

2017-05-22 12:47 UTC, GendoIkari commented on tests/test_favorite.py
> +def create_an_user(id_user, number):
Articoli, preposizioni, etc..., e' difficile che si mettano nei nomi. Di solito la forma piu' dichiarativa possibile e' la migliore: `create_user`, `create_item`.

2017-05-22 12:47 UTC, GendoIkari commented on tests/test_favorite.py
> +        assert len(json.loads(resp.data.decode())) == 1
`data = json.loads(resp.data.decode())`
E poi usiamo data, che dici?

2017-05-22 12:47 UTC, GendoIkari commented on tests/test_favorite.py
> +        assert not json.loads(resp.data.decode())
`assert len(data) == 0`

2017-05-26 10:04 UTC, GendoIkari commented on models.py
> +
Queste non le usi, rimuovere.

2017-05-26 10:04 UTC, GendoIkari commented on models.py
> +
Anche questa mi pareva si avesse detto che era un po' inutile, no? Vabbe' possiamo anche tenerla pero' chiamiamola semplicemente `count`.
```Item.count()```

E diventa:
```python
return cls.select().count()
```

2017-05-26 10:04 UTC, GendoIkari commented on models.py
> +class Favorites(BaseModel):
Diamo a questo Favorites un `uuid`.

2017-06-05 12:18 UTC, gvaldambrini requested changes

2017-06-05 12:18 UTC, gvaldambrini commented on models.py
> +        Favorites.delete().where(Favorites.item == item).where(Favorites.user == self).execute()
potevi mettere entrambe le condizioni in un unico where separato da una virgola, come mostrato qua:
```
http://docs.peewee-orm.com/en/latest/peewee/querying.html#filtering-records
```

2017-06-05 12:18 UTC, gvaldambrini commented on tests/test_favorite.py
> +class TestFavorites:
potevi derivare da BaseTest e aggiungere i favoriti alle tabelle da creare?

2017-06-05 12:18 UTC, gvaldambrini commented on tests/test_favorite.py
> +        assert resp.status_code == NOT_FOUND
????
se non ho preferiti perché devo avere un not_found? il not found indica che la risorsa non esiste, non che è vuota.

2017-06-05 12:18 UTC, gvaldambrini commented on tests/test_favorite.py
> +        assert resp.status_code == NOT_FOUND
BAD_REQUEST. NOT_FOUND indica che la risorsa in oggetto non esiste.

2017-06-05 12:18 UTC, gvaldambrini commented on tests/test_favorite.py
> +        assert resp.status_code == NOT_FOUND
stessa storia di sopra

2017-06-12 12:47 UTC, GendoIkari commented on tests/test_favorite.py
> +        )
Questi due metodi sono duplicati di BaseTest.

2017-06-12 12:47 UTC, GendoIkari commented on tests/test_favorite.py
> +        id_item = uuid.uuid4()
E' ridontante. create_user fa gia' questa cosa.

2017-06-12 12:47 UTC, GendoIkari commented on views/favorites.py
> +        # TODO: we will have a user from auth here.
Questo commento ora e' superfluo.

2017-06-12 12:47 UTC, GendoIkari commented on views/favorites.py
> +        # TODO: we will have a user from auth here.
Idem.

2017-06-12 13:25 UTC, merged