user views
mwcschool/ecommerce_api pull request #5
Opened 2017-05-05 14:53 UTC by iryko

Implements #2

2017-05-05 15:14 UTC, gvaldambrini requested changes

2017-05-05 15:14 UTC, gvaldambrini commented on app.py
> +api.add_resource(UserResource, '/user/<uuid:user_id>')
questo dovrebbe essere `/users/...`

2017-05-05 15:14 UTC, gvaldambrini commented on models.py
> +        }
ma non s'era detto di ritornare solo lo `user_id`?

2017-05-05 15:14 UTC, gvaldambrini commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<chiocciola>@)[a-z]{3,}\.[a-z]{2,}')
evitiamo termini in italiano nel codice 😄

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +    def test_post__empty(self):
ma non sarebbe success? perché empty?

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
c'è qualcosa che non mi torna. Viene creato un utente attraverso la `User.create`, poi un altro utente viene creato con la `post`, quindi gli utenti totali dovrebbero essere 2. Ma il valore di ritorno della post dovrebbe tornare un unico utente (o meglio, come detto sopra solo l'id dell'utente creato), quindi come fa a funzionare?

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +            )
questa parentesi tonda dovrebbe essere indentata al livello di `User.create`

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        assert resp.status_code == BAD_REQUEST
è necessario anche controllare che non sia creato un utente per sbaglio verificando su database

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +    def test_post__field_not_exist(self):
se è al singolare, ci vuole la s: `test_post__field_not_exists`

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
è necessario verificare che l'utente sia stato modificato correttamente (dal test nessuno mi garantisce che se gli invio al server `bla bla` lui vada a scrivere `ble ble`)

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
bisogna verificare che quanto salvato su database sia effettivamente quanto inviato al server

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        )
a cosa serve la creazione di questo oggetto?

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        )
come per il test precedente, a cosa serve creare un oggetto?

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        resp = self.app.delete('/user/{}'.format(obj1.user_id))
a cosa servono data_1 e data_2?

2017-05-05 15:14 UTC, gvaldambrini commented on tests/test_user.py
> +        assert len(User.select().where(User.user_id == obj2.user_id)) == 1
non c'è bisogno di fare 2 query qua. Si potrebbe salvare il valore di ritorno della `User.select()` e verificare che:
 * sia ritornato un unico utente
 * l'utente ritornato sia effettivamente quello non cancellato

2017-05-05 15:38 UTC, iryko commented on app.py
> +api.add_resource(UserResource, '/user/<uuid:user_id>')
ok

2017-05-08 12:18 UTC, iryko commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<chiocciola>@)[a-z]{3,}\.[a-z]{2,}')
ok

2017-05-08 12:20 UTC, iryko commented on tests/test_user.py
> +    def test_post__field_not_exist(self):
ok

2017-05-08 12:24 UTC, iryko commented on tests/test_user.py
> +        resp = self.app.delete('/user/{}'.format(obj1.user_id))
ok

2017-05-08 12:24 UTC, iryko commented on tests/test_user.py
> +            )
ok

2017-05-08 13:40 UTC, iryko commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
ok

2017-05-08 13:48 UTC, iryko commented on tests/test_user.py
> +        assert resp.status_code == BAD_REQUEST
ok

2017-05-08 14:31 UTC, iryko commented on models.py
> +        }
ok

2017-05-08 14:31 UTC, iryko commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
ok

2017-05-08 14:32 UTC, iryko commented on tests/test_user.py
> +    def test_post__empty(self):
ok

2017-05-08 14:37 UTC, iryko commented on tests/test_user.py
> +        assert query == json.loads(resp.data.decode())
ok

2017-05-08 14:52 UTC, iryko commented on tests/test_user.py
> +        assert len(User.select().where(User.user_id == obj2.user_id)) == 1
ok

2017-05-08 15:28 UTC, GendoIkari commented on tests/test_user.py
> +        assert resp.status_code == BAD_REQUEST
```python
assert len(User.select()) == 0
```

2017-05-08 15:28 UTC, GendoIkari commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<at>@)[a-z]{3,}\.[a-z]{2,}')
Aggiungere test per questa feature: mandiamo una email non valida e vediamo che sia bad_request.

2017-05-08 15:28 UTC, GendoIkari commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<at>@)[a-z]{3,}\.[a-z]{2,}')
Creiamo una funzioncina valid_email() che torna true o false.

2017-05-09 12:37 UTC, alecappe commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<at>@)[a-z]{3,}\.[a-z]{2,}')
ok

2017-05-09 12:37 UTC, alecappe commented on tests/test_user.py
> +        assert resp.status_code == BAD_REQUEST
ok

2017-05-09 12:49 UTC, alecappe commented on views/user.py
> +        regex = re.compile('[a-z]{3,}(?P<at>@)[a-z]{3,}\.[a-z]{2,}')
ok

2017-05-09 14:41 UTC, gvaldambrini commented on tests/test_user.py
> +        user_from_db = User.get()
ma che bisogno c'è di fare questa query? Già viene fatta una query alla riga prima, che bisogno c'è di rifarne un'altra?

2017-05-09 14:52 UTC, alecappe commented on tests/test_user.py
> +        user_from_db = User.get()
ok

2017-05-09 15:02 UTC, gvaldambrini approved these changes

2017-05-09 15:02 UTC, merged